################################################################################
# Makefile
#
# Environment variables:
#     CROSS_COMPILE - string to be prepended to toolchain used to build
#
#     ARCH - architecture to build for. Used to include architecture specific 
#		code from arch/ subdirectory.
#
################################################################################
CROSS_COMPILE?=
ARCH?=arm

AS:=$(CROSS_COMPILE)as
CC:=$(CROSS_COMPILE)gcc
LD:=$(CROSS_COMPILE)ld

ASFLAGS+=-c -I./include -I./arch/$(ARCH)/include -D__ASSEMBLY__ -mcpu=cortex-a7
CFLAGS+=-ffreestanding -Wall -Wextra -Werror -nostdlib -nostartfiles -mcpu=cortex-a7 -g \
	-I./include -I./arch/$(ARCH)/include

Q:=@-

.SUFFIXES:

# objects required to build kernel. Add an dependency via +=
kernel-obj:=

# include arch specific code
include arch/$(ARCH)/Makefile
include main/Makefile
include lib/Makefile
include tests/Makefile

.PHONY: all clean distclean kernel TAGS FORCE

default: uImage

all: kernel uImage

clean:
	$(Q)echo " [RM] *.o"
	$(Q)rm $(kernel-obj) 
	$(Q)rm $(kernel-obj:.o=.d)
	$(Q)echo " [RM] kernel"
	$(Q)rm kernel kernel.bin uImage

distclean: clean

TAGS:
	$(Q)find . -name '*.c' | etags -
	$(Q)find . -name '*.h' | etags --append -
	$(Q)find . -name '*.S' | etags --append -


###
# Specfic build targets
###

kernel: $(kernel-obj)
	$(Q)echo " [LD] $@"
	$(Q)$(LD) $(LDFLAGS) -T arch/$(ARCH)/link.lds -o $@ $(kernel-obj)

uImage: kernel
	$(Q)$(CROSS_COMPILE)objcopy -O binary kernel kernel.bin
	$(Q)mkimage -A $(ARCH) -T kernel -C none -a 0x40008000 -d kernel.bin uImage

docs: FORCE
	$(Q)mkdir docs/
	$(Q)doxygen doxyfile

###
# Build templates
###
.SUFFIXES:
.SUFFIXES: .c .o .S

# Include dependency files generated by gcc (-MM flag)
-include $(kernel-obj:.o=.d)

.S.o:
	$(Q)echo " [AS] $@"
	$(Q)$(CC) $(ASFLAGS) -o $@ $<
	$(Q)$(CC) $(ASFLAGS) -MM $< > $*.d
	$(Q)mv $*.d $*.d.tmp
	$(Q)sed -e 's|.*:|$*.o:|' < $*.d.tmp > $*.d
	$(Q)rm $*.d.tmp

.c.o:
	$(Q)echo " [CC] $@"
	$(Q)$(CC) $(CFLAGS) -c -o $@ $<
	$(Q)$(CC) $(CFLAGS) -MM $< > $*.d
	$(Q)mv $*.d $*.d.tmp
	$(Q)sed -e 's|.*:|$*.o:|' < $*.d.tmp > $*.d
	$(Q)rm $*.d.tmp

